### ISSUE TITLE
Question: What is the purpose of the AsyncAgiServer

### ISSUE THREAD

**Issue by zaidqureshi2** [tcncloud/agi-node#11]
Hey just wanted to know the purpose of the async agi server

**Comment by sigxcpu76** [comment]
AsyncAGI is based on AMI instead of AGI.

Instead of asterisk calling AGI port on the app (4573), the app connects to Asterisk on AMI port (5038).
If you use both AMI & AGI, a single connection is required in this case, from app to Asterisk on AMI port.

**Comment by zaidqureshi2** [comment]
Thanks, would you guys know of a way I can get a stream of the real time audio

**Comment by sigxcpu76** [comment]
You should check EAGI but it is outside the scope of this project.
