### ISSUE TITLE
Can I get arguments passed to mapped script ?

### ISSUE THREAD

**Issue by frenzymind** [tcncloud/agi-node#13]
Hello.
Asterisk can call AGI with arguments:
`AGI(command[,arg1[,arg2[,…]]])`
If I call agi from dial plan like this:
`exten => _X.,1,AGI(agi://localhost:3000/myscript, 1,2,3)`
Can I get these 1,2,3 somewhere in my myscript ?
Thanks!

**Comment by sigxcpu76** [comment]
Try `channel.request.arg_0`, `channel.request.arg_1` and so on.
`channel.request` should point to the entire AGI env, from which you can pull data as `channel.request.X` where `X` is the field name with prefix `agi_` removed.

https://www.voip-info.org/asterisk-agi/
