### ISSUE TITLE
add listener

### ISSUE THREAD

**Issue by iatalmid** [tcncloud/agi-node#2]
Hello,
how can I add listener, for example onHangup?
When the call will be finished, I need to calculate it.

Can I do like this

function testScript(channel) {
 channel.on("hangup", function(){
    // do something....
});
}

**Comment by sigxcpu76** [comment]
Channel events belong to AMI function, not AGI.
For example, `agi-node` uses https://www.npmjs.com/package/asterisk-manager for the `agi:async` implementation.
