### ISSUE TITLE
Can't select specific function inside script

### ISSUE THREAD

**Issue by JulianGerhard** [tcncloud/agi-node#4]
Hi,

the script works as expected, but how can i decide, which function inside to call? Example:

I've got the extension calls:

exten => 1234,n,agi(agi://127.0.0.1/submitgs);
exten => 1234,n,agi(agi://127.0.0.1/receivetts);

And now I want the node.js - File to listen on port 4573 and execute either function submitgs or receivetts - but how?

If I write:

var server = new AGIServer(script, 4573);

script isnt found and if I write one of the functions, only this one is executed?

Thank you for your help!

**Comment by sigxcpu76** [comment]
All the AGI request variables are passed upon the dispatcher script (check README).
What you are looking for is `agi_request`, which can be extracted as `channel.request.request`

**Comment by JulianGerhard** [comment]
That helped, thank you very much!
